# Generated by Django 5.1.2 on 2024-11-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_realestate_delete_realestatedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='BHK',
            new_name='bhk',
        ),
    ]
